- id: '1656602421770'
  alias: Feedback - Acknowledge for Heat Wave
  description: ''
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: /ack_heat_wave
  condition: []
  action:
  - service: alert.turn_off
    data: {}
    target:
      entity_id: alert.heat_wave_detected_warning_alert_active
  - service: telegram_bot.answer_callback_query
    data:
      show_alert: false
      message: Alert Stop
      callback_query_id: '{{ trigger.event.data.id }}'
  mode: single


- id: '1659882653673'
    alias: Notify_Information conditional
    description: ''
    trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: notify
        service: Notify_Information
    condition:
    - condition: state
      entity_id: binary_sensor.im_at_home
      state: 'on'
    action:
    - service: notify.telegram_me
      data:
        message: '{{ trigger.event.data.service_data.message }}'
    mode: single
